# Generated by Django 5.2.6 on 2025-09-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='direccion',
            field=models.CharField(default='Dirección no especificada', max_length=255),
        ),
    ]
