# Generated by Django 5.2.6 on 2025-09-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitud_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categorias',
            field=models.CharField(choices=[('sin_categoria', 'Sin_Categoria'), ('cocina', 'Cocina'), ('bano', 'Baño'), ('exterior', 'Exterior'), ('living_comedor', 'Living & Comedor'), ('taller', 'Taller'), ('habitacion', 'Habitación')], default='sin categoria', max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Altura del muebre en metros(sin ajustar)', max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_mueble',
            field=models.CharField(choices=[('standard', 'Standard (Sin fórmula)'), ('mesa_taller', 'Mesa de Taller'), ('escritorio', 'Escritorio'), ('lavamanos', 'Lavamanos'), ('lavaplatos', 'Lavaplatos'), ('librero', 'Librero')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='altura_usuario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='precio_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
