# Generated by Django 5.2.6 on 2025-10-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_mueble',
            field=models.CharField(choices=[('standard', 'Standard'), ('mesa_taller', 'Mesa de Taller'), ('escritorio', 'Escritorio'), ('lavamanos', 'Lavamanos'), ('lavaplatos', 'Lavaplatos'), ('librero', 'Librero')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (mayor número = más prioritario)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destacados', to='core.producto', verbose_name='Producto destacado')),
            ],
            options={
                'verbose_name': 'Producto destacado',
                'verbose_name_plural': 'Productos destacados',
                'ordering': ['-orden', '-fecha_creacion'],
            },
        ),
    ]
