# Generated by Django 5.2 on 2025-10-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_categoria_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_mueble',
            field=models.CharField(choices=[('standard', 'Standard'), ('mesa taller', 'Mesa de Taller'), ('escritorio', 'Escritorio'), ('lavamanos', 'Lavamanos'), ('lavaplatos', 'Lavaplatos'), ('librero', 'Librero')], default='standard', max_length=20),
        ),
    ]
