# Generated by Django 5.2 on 2025-10-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_producto_tipo_mueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categorias',
            field=models.CharField(choices=[('sin categoria', 'SinCategoria'), ('cocina', 'Cocina'), ('bano', 'Baño'), ('exterior', 'Exterior'), ('living comedor', 'Living & Comedor'), ('taller', 'Taller'), ('habitacion', 'Habitación')], default='sin categoria', max_length=30),
        ),
    ]
