# Generated by Django 5.2 on 2025-10-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_categoria_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='direccion',
        ),
    ]
