# Generated by Django 5.2.6 on 2025-10-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_solicitud_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej:'Oferta de Invierno', 'Liquidación Final' ", max_length=100)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuentos(ej: 15 para un 15%)', max_digits=5)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=False)),
                ('productos', models.ManyToManyField(blank=True, related_name='ofertas', to='core.producto')),
            ],
        ),
    ]
