# Generated by Django 5.2 on 2025-10-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categorias',
            field=models.CharField(choices=[('sin categoria', 'SinCategoria'), ('cocina', 'Cocina'), ('bano', 'Baño'), ('exterior', 'Exterior'), ('living comedor', 'Living & Comedor'), ('taller', 'Taller'), ('habitacion', 'Habitación'), ('ofertas', 'Ofertas')], default='sin categoria', max_length=30),
        ),
    ]
