# Generated by Django 6.0 on 2025-12-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_categoria_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_secundaria_1',
            field=models.ImageField(blank=True, null=True, upload_to='producto/secundarias/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_secundaria_2',
            field=models.ImageField(blank=True, null=True, upload_to='producto/secundarias/'),
        ),
    ]
